// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: distribution_tx.proto

#include "distribution_tx.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace cosmos {
namespace distribution {
namespace v1beta1 {
class MsgWithdrawDelegatorRewardDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MsgWithdrawDelegatorReward> _instance;
} _MsgWithdrawDelegatorReward_default_instance_;
}  // namespace v1beta1
}  // namespace distribution
}  // namespace cosmos
static void InitDefaultsscc_info_MsgWithdrawDelegatorReward_distribution_5ftx_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::cosmos::distribution::v1beta1::_MsgWithdrawDelegatorReward_default_instance_;
    new (ptr) ::cosmos::distribution::v1beta1::MsgWithdrawDelegatorReward();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_MsgWithdrawDelegatorReward_distribution_5ftx_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_MsgWithdrawDelegatorReward_distribution_5ftx_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_distribution_5ftx_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_distribution_5ftx_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_distribution_5ftx_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_distribution_5ftx_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::cosmos::distribution::v1beta1::MsgWithdrawDelegatorReward, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::cosmos::distribution::v1beta1::MsgWithdrawDelegatorReward, delegator_address_),
  PROTOBUF_FIELD_OFFSET(::cosmos::distribution::v1beta1::MsgWithdrawDelegatorReward, validator_address_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::cosmos::distribution::v1beta1::MsgWithdrawDelegatorReward)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::cosmos::distribution::v1beta1::_MsgWithdrawDelegatorReward_default_instance_),
};

const char descriptor_table_protodef_distribution_5ftx_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025distribution_tx.proto\022\033cosmos.distribu"
  "tion.v1beta1\"R\n\032MsgWithdrawDelegatorRewa"
  "rd\022\031\n\021delegator_address\030\001 \001(\t\022\031\n\021validat"
  "or_address\030\002 \001(\tb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_distribution_5ftx_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_distribution_5ftx_2eproto_sccs[1] = {
  &scc_info_MsgWithdrawDelegatorReward_distribution_5ftx_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_distribution_5ftx_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_distribution_5ftx_2eproto = {
  false, false, descriptor_table_protodef_distribution_5ftx_2eproto, "distribution_tx.proto", 144,
  &descriptor_table_distribution_5ftx_2eproto_once, descriptor_table_distribution_5ftx_2eproto_sccs, descriptor_table_distribution_5ftx_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_distribution_5ftx_2eproto::offsets,
  file_level_metadata_distribution_5ftx_2eproto, 1, file_level_enum_descriptors_distribution_5ftx_2eproto, file_level_service_descriptors_distribution_5ftx_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_distribution_5ftx_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_distribution_5ftx_2eproto)), true);
namespace cosmos {
namespace distribution {
namespace v1beta1 {

// ===================================================================

class MsgWithdrawDelegatorReward::_Internal {
 public:
};

MsgWithdrawDelegatorReward::MsgWithdrawDelegatorReward(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward)
}
MsgWithdrawDelegatorReward::MsgWithdrawDelegatorReward(const MsgWithdrawDelegatorReward& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  delegator_address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_delegator_address().empty()) {
    delegator_address_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_delegator_address(), 
      GetArena());
  }
  validator_address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_validator_address().empty()) {
    validator_address_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_validator_address(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward)
}

void MsgWithdrawDelegatorReward::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MsgWithdrawDelegatorReward_distribution_5ftx_2eproto.base);
  delegator_address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  validator_address_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

MsgWithdrawDelegatorReward::~MsgWithdrawDelegatorReward() {
  // @@protoc_insertion_point(destructor:cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MsgWithdrawDelegatorReward::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  delegator_address_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  validator_address_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void MsgWithdrawDelegatorReward::ArenaDtor(void* object) {
  MsgWithdrawDelegatorReward* _this = reinterpret_cast< MsgWithdrawDelegatorReward* >(object);
  (void)_this;
}
void MsgWithdrawDelegatorReward::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MsgWithdrawDelegatorReward::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MsgWithdrawDelegatorReward& MsgWithdrawDelegatorReward::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MsgWithdrawDelegatorReward_distribution_5ftx_2eproto.base);
  return *internal_default_instance();
}


void MsgWithdrawDelegatorReward::Clear() {
// @@protoc_insertion_point(message_clear_start:cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  delegator_address_.ClearToEmpty();
  validator_address_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MsgWithdrawDelegatorReward::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string delegator_address = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_delegator_address();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward.delegator_address"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string validator_address = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_validator_address();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward.validator_address"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MsgWithdrawDelegatorReward::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string delegator_address = 1;
  if (this->delegator_address().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_delegator_address().data(), static_cast<int>(this->_internal_delegator_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward.delegator_address");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_delegator_address(), target);
  }

  // string validator_address = 2;
  if (this->validator_address().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_validator_address().data(), static_cast<int>(this->_internal_validator_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward.validator_address");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_validator_address(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward)
  return target;
}

size_t MsgWithdrawDelegatorReward::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string delegator_address = 1;
  if (this->delegator_address().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_delegator_address());
  }

  // string validator_address = 2;
  if (this->validator_address().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_validator_address());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MsgWithdrawDelegatorReward::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward)
  GOOGLE_DCHECK_NE(&from, this);
  const MsgWithdrawDelegatorReward* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MsgWithdrawDelegatorReward>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward)
    MergeFrom(*source);
  }
}

void MsgWithdrawDelegatorReward::MergeFrom(const MsgWithdrawDelegatorReward& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.delegator_address().size() > 0) {
    _internal_set_delegator_address(from._internal_delegator_address());
  }
  if (from.validator_address().size() > 0) {
    _internal_set_validator_address(from._internal_validator_address());
  }
}

void MsgWithdrawDelegatorReward::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgWithdrawDelegatorReward::CopyFrom(const MsgWithdrawDelegatorReward& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgWithdrawDelegatorReward::IsInitialized() const {
  return true;
}

void MsgWithdrawDelegatorReward::InternalSwap(MsgWithdrawDelegatorReward* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  delegator_address_.Swap(&other->delegator_address_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  validator_address_.Swap(&other->validator_address_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata MsgWithdrawDelegatorReward::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1beta1
}  // namespace distribution
}  // namespace cosmos
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::cosmos::distribution::v1beta1::MsgWithdrawDelegatorReward* Arena::CreateMaybeMessage< ::cosmos::distribution::v1beta1::MsgWithdrawDelegatorReward >(Arena* arena) {
  return Arena::CreateMessageInternal< ::cosmos::distribution::v1beta1::MsgWithdrawDelegatorReward >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
